project:
  type: website

website:
  title: "Poetry Post Mapping Project"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti



