project:
  type: website
  output-dir: .

website:
  title: "Poetry Post Mapping Project"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - list_print.qmd
      - about.qmd
      - get_involved.qmd

format:
  html:
    theme: yeti



